### ISSUE TITLE
Error when loading smplx model

### ISSUE THREAD

**Issue by YananSunn** [facebookresearch/body2hands#11]
Hi, thanks for the fantastic work!

When I tried the SMPLx Plug-in Demo with the command `python -m smplx_plugin.demo --checkpoint models/ours_wb_arm2wh_checkpoint.pth --data_dir video_data/Multi/conan_frank/mocap/ --tag 'mocap_'`, I met this error:

Traceback (most recent call last):
  File "/home/sunyn/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/sunyn/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/sunyn/MotionInBetween/body2hands/smplx_plugin/demo.py", line 166, in <module>
    main(args)
  File "/data/sunyn/MotionInBetween/body2hands/smplx_plugin/demo.py", line 50, in main
    test_X, total_body, total_cam = load_smplx(args.data_dir)
  File "/data/sunyn/MotionInBetween/body2hands/smplx_plugin/demo.py", line 142, in load_smplx
    body = aa_to_rot6d(body)
  File "/data/sunyn/MotionInBetween/body2hands/utils/load_utils.py", line 100, in aa_to_rot6d
    np_mat = np_mat.as_dcm()
AttributeError: 'scipy.spatial.transform.rotation.Rotation' object has no attribute 'as_dcm'

I have not changed any code and already downloaded all the required files. Besides, the Testing with pretrained models works well. I have no idea how to fix this bug.  Could you please give me some advice? Thanks a lot.

**Comment by YananSunn** [comment]
I fixed this bug. As mentioned in https://docs.scipy.org/doc/scipy/release.1.4.0.html: In scipy.spatial.Rotation methods from_dcm, as_dcm were renamed to from_matrix, as_matrix respectively. The old names will be removed in SciPy 1.6.0. 

Changing utils/load_utils.py line 100 as_dcm to as_matrix will make the code work well.

I guess that changing the version of SciPy could work too, but I have not tried this method.

It will be better if you can make the requirement.txt with the versions of the required package. :-)
